Pushing local changes and the fix for the modal
gcivil-nyu-org/Team_Team6_CS-GY-6063-Fall2021 pull request #180
Opened 2021-11-24 23:45 UTC by azraf-a

Tag collapsible.

Currently set to slice the cat list and display the first 3 categories.

On clicking view all tags, you'll be able to see everything.

2021-11-25 00:10 UTC, azraf-a commented on creation/templates/creation/_search_results.html
> +                <div class="modal" id="modal_{{ business.id }}" style="z-index:2000">
Fix for modal-map overlap.

2021-11-25 00:10 UTC, azraf-a commented on dayplanner/templates/dayplanner/_navbar.html
> -        <a class="navbar-item"> <!-- PLACEHOLDER FOR BUTTON TO DAY CURATION AND RANKING -->
Got rid of redundant href in navbar.

2021-11-25 00:11 UTC, azraf-a commented on explore/templates/explore/cat_panel.html
> +<style>
CSS to make elements collapsible.

2021-11-25 00:11 UTC, azraf-a commented on explore/templates/explore/cat_panel.html
> +<div class="column has-text-centered">
Slicing loop to only show first three cats.

2021-11-25 00:11 UTC, azraf-a commented on explore/templates/explore/cat_panel.html
> +
JS for collapsibles.

2021-11-25 00:26 UTC, sballan requested changes
Cool stuff!

Left a few comments - mostly around making use of Bulma.  In particular, it's important not to redefine the CSS class "content", because this is already defined by Bulma.

2021-11-25 00:26 UTC, sballan commented on explore/templates/explore/cat_panel.html
> +    .collapsible {
I don't think we need any of these styles to make a panel collapsible, right? Was there something you needed that Bulma didn't have?

2021-11-25 00:26 UTC, sballan commented on explore/templates/explore/cat_panel.html
> +      padding: 0 18px;
Same comment as above for this `padding` class.  For the Bulma way of adding padding, see https://bulma.io/documentation/helpers/spacing-helpers/

2021-11-25 00:26 UTC, sballan commented on explore/templates/explore/cat_panel.html
> +        <a class="tag is-success is-light" style="margin-right: 5px;" href="/explore">Reset</a>
Instead of manual styling here, consider using [Bulma's spacing helpers](https://bulma.io/documentation/helpers/spacing-helpers/).  I think the class to add here would be something like `mr-1`

2021-11-25 00:26 UTC, sballan commented on explore/templates/explore/cat_panel.html
> +            {% for cat in cats %}
We have category duplication here, since the first three categories will already be on the page. Can we slice starting after the first 3 categories? Or have the original categories disappear when this panel opens?

2021-11-25 00:26 UTC, sballan commented on explore/templates/explore/cat_panel.html
> +            <a class="tag is-warning" style="margin-right: 5px;" href="/explore/search/{{ cat.cat }}"> {{ cat.cat }}</a>
I think the Bulma class to add here would be something like `mr-1`

2021-11-25 16:29 UTC, azraf-a commented on explore/templates/explore/cat_panel.html
> +            {% for cat in cats %}
Modified to start the slice inside the collapsible after the 3 category accordingly.

2021-11-25 16:29 UTC, azraf-a commented on explore/templates/explore/cat_panel.html
> +            <a class="tag is-warning" style="margin-right: 5px;" href="/explore/search/{{ cat.cat }}"> {{ cat.cat }}</a>
Changed custom spacing stylings to use mt and mr from Bulma docs.

2021-11-25 16:30 UTC, azraf-a commented on explore/templates/explore/cat_panel.html
> +        <a class="tag is-success is-light" style="margin-right: 5px;" href="/explore">Reset</a>
Changed custom spacing stylings to use mt and mr from Bulma docs.

2021-11-25 16:33 UTC, azraf-a commented on explore/templates/explore/cat_panel.html
> +    .content {
Modified the class to be named "collapse-content" to clarify. The class is just a container w/overflow hidden and its max height set to 0 initially. The JS script I added for the collapsible works by identifying the next element after the button marked "collapsible" and expanding it out from its default hidden state. This wasn't meant to mirror or modify a Bulma class; just bad naming convention on my part. 

Fixed it accordingly.

2021-11-25 16:34 UTC, azraf-a commented on explore/templates/explore/cat_panel.html
> +    .collapsible {
This class works in conjunction w/the script I added to the page to identify the next element and expand it - works in tandem with the collapse-content class to give the effect of an expanding collapsible card.

2021-11-25 16:34 UTC, azraf-a commented on explore/templates/explore/cat_panel.html
> +      padding: 0 18px;
N/A here

2021-11-25 18:48 UTC, sballan commented on explore/templates/explore/cat_panel.html
> +    .collapsible {
I see what you mean: you put the `collapsible` class on the element you want to click on, and then you use that class to find the element with javascript, so you can then add the event listener for clicking. The class is therefore used to identify the element you want to click on.  

With the CSS `.collapsible {...}`, you've added additional styles to any element with the `collapsible` class. My comment was about the styles this CSS adds to elements with the class `collapsible`.     Since these styles are not used for collapsing, I was wondering whether any styles you wanted could be applied to `collapsible` elements using Bulma classes directly on those elements.

2021-11-25 18:50 UTC, sballan commented on explore/templates/explore/cat_panel.html
> +      padding: 0 18px;
I'm not sure what your reply means, would you mind explaining?

2021-11-29 21:06 UTC, sballan approved these changes
Looks great!

2021-11-29 22:01 UTC, merged