Travis setup
gcivil-nyu-org/Team_Team6_CS-GY-6063-Fall2021 pull request #82
Opened 2021-10-21 22:04 UTC by wangsnuxiao

2021-10-21 22:24 UTC, wangsnuxiao commented
Tested all functionality after formatting.

2021-10-23 00:39 UTC, sballan commented on .travis.yml
> +  - black --check .
Looks great!

I just had this idea - looks like some of the travis script will do things we all want to do locally (like formatting), and some things that only need to happen on travis (like migrating).  What if we put all code formatting and test checks in a script file, and then invoke the script here? Would be cool to easily reproduce what Travis will do when we deploy, right from our local machines, so we can fix things before we push.

Eg, a file called something like `deploy_checks.sh`
```
python -m black --check .
coverage run --source='.' manage.py test
```

Then, you could add a line to the script like:
```
script:
...
  - ./deploy_checks.sh
...
```

and locally, we could all do 
```
$ docker compose run web ./deploy_checks.sh
```

2021-10-23 00:40 UTC, sballan commented on .travis.yml
> +  - docker-compose run web python manage.py migrate
Be careful about `docker-compose` vs `docker compose`.  

I _think_ the latest version of docker should use `docker compose`.

2021-10-23 00:43 UTC, wangsnuxiao commented on .travis.yml
> +  - docker-compose run web python manage.py migrate
Oh! that is a great point.

2021-10-23 00:45 UTC, wangsnuxiao commented on .travis.yml
> +  - black --check .
Do you mean to set up something like a local container to emulate the Travis CI locally?

2021-10-23 01:08 UTC, sballan requested changes
This is great!

Be sure to add `flake8` to the travis script - otherwise, looks ready

2021-10-23 01:36 UTC, wangsnuxiao commented
Will do!

2021-10-24 00:28 UTC, merged