Issue 24 95
gcivil-nyu-org/Team_Team6_CS-GY-6063-Fall2021 pull request #99
Opened 2021-11-02 04:03 UTC by wangsnuxiao

Integrated Issue 24 and Issue 95 with Joe and Kevin.
Travis-Build fixed and passed

2021-11-02 17:18 UTC, azraf-a approved these changes

2021-11-02 17:34 UTC, sballan requested changes
Looks great so far!

I left some questions

2021-11-02 17:34 UTC, sballan commented on .travis.yml
> +  - pip install coverage==4.5.4
This is unneeded, since it is in requirements-dev.txt

2021-11-02 17:34 UTC, sballan commented on creation/static/map.js
> +    map = L.map('map').setView([40.7342, -74.0033], 13);
What are these hardcoded coordinates?  We should avoid them if we can.  

If you need a default coordinate set, consider using the user's geolocation.

2021-11-02 17:34 UTC, sballan commented on creation/templates/creation/_day_list.html
> +                <a href="/creation/delete_day?day_id={{ day.id }}" class="button is-danger"> Delete</a>
Consider using the same pattern as we used for editing: `/creation/edit/{{ day.id }}`.  Having a single set of conventions makes the code easier to understand

2021-11-02 17:34 UTC, sballan commented on creation/templates/creation/mappage.html
> +    <script src="{% static 'map.js' %}"></script>
I see that we're putting a `script` tag in the body here, but we're putting a different `script` tag in the `link` block above.  

I think there are tradeoffs to either method - last I remember looking into this, the standard practice was to put javascript in the `body` tag, but I could be wrong.

I don't have a strong opinion about where, but can we make a decision about where all javascript belongs?

2021-11-02 17:34 UTC, sballan commented on creation/urls.py
> +    path("delete_day", views.deleteday),
I see, I think you were using a URL param here instead.  Consider sticking to a single convention for things like this, it makes the code easier to understand.

2021-11-02 17:34 UTC, sballan commented on creation/views.py
> +@login_required(login_url="/authentication/login")
Love this guard!

2021-11-02 17:34 UTC, sballan commented on resources/days/migrations/0001_initial.py
> +        migrations.CreateModel(
Why are we adding dayvenues to this migration file?  This will break our database.  

It's not the end of the world to break our database, because at this stage we can rebuild it, but do we have to?

2021-11-02 17:34 UTC, sballan commented on resources/days/migrations/0002_dayvenue.py
> -    operations = [
Do we need to delete this file?  See my other comment

2021-11-02 17:34 UTC, sballan commented on resources/venues/migrations/0001_initial.py
> +                ("yelp_id", models.CharField(max_length=100, unique=True)),
nice - this was needed!

2021-11-02 17:34 UTC, sballan commented on resources/venues/migrations/0002_alter_venue_yelp_id.py
> -# Generated by Django 3.2.8 on 2021-10-16 20:37
Why delete migrations that are already run on heroku?  I don't think we need to delete any migrations.

2021-11-02 17:39 UTC, sballan commented
One last thought - keep an eye on the [test coverage](https://coveralls.io/github/gcivil-nyu-org/Team_Team6_CS-GY-6063-Fall2021?branch=issue_24_95), which is currently at 83%

2021-11-02 17:41 UTC, wangsnuxiao commented on creation/views.py
> +@login_required(login_url="/authentication/login")
XD

2021-11-02 17:42 UTC, wangsnuxiao commented on resources/days/models.py
> +    is_active = models.BooleanField("is_active", default=True)
For pseudo deletion

2021-11-02 17:43 UTC, wangsnuxiao commented on resources/days/models.py
> +    is_active = models.BooleanField("is_active", default=True)
When delete we set Day.is_active = False
When accessing all the Day we use a filter ("is_active"=True)

2021-11-02 17:45 UTC, sballan commented on resources/days/models.py
> +    is_active = models.BooleanField("is_active", default=True)
Right - I understand you are doing pseudo deletion, my question is why do pseudo deletion?  What is the intended purpose of days that have been pseudo deleted?

2021-11-02 17:45 UTC, wangsnuxiao commented on creation/views.py
> +        day.is_active = False
This way the Admin is able to "Hide" a post without really destroy.
 We have the ability to bring a deleted Day back online.

2021-11-02 17:46 UTC, sballan commented on creation/views.py
> +        day.is_active = False
Why would we want to do this?

2021-11-02 17:49 UTC, wangsnuxiao commented on resources/days/models.py
> +    is_active = models.BooleanField("is_active", default=True)
This way, we can delete a Day without actually destroying it. If needed we can "Put back" the day. However, this would need an authorized user like Admin to do so. Also by doing this, the admin can temporarily ban a post.

2021-11-02 17:59 UTC, sballan commented on resources/days/models.py
> +    is_active = models.BooleanField("is_active", default=True)
I see - the purpose is for content moderation?

Content Moderation is an Epic we haven’t gotten to yet, and in my opinion deserves a group discussion.  It’s a cool idea to use a Boolean flag like this, but in my opinion this is out of scope for this ticket. Remembering to filter on that flag every time we query for Days introduces overhead before we’ve even decided on how our content moderation policy will work.  We might decide to do it very differently!

As an example, consider this: the only user content for a Day is the Day’s name. Perhaps we decide to make a separate model called “user text”, which has its own “active” flag, and use this for a Day’s name. This way - we could ban the name of a day, without banning the entire day itself. 

I’m not saying we should necessarily do it this way - I’m just giving an example of a different solution that would make this work invalid.

2021-11-02 18:02 UTC, sballan commented on resources/days/models.py
> +    is_active = models.BooleanField("is_active", default=True)
So just to clarify - I’m not putting my foot down here, I just wanted to voice my opinions on this matter. If you still want to keep it in, I’ll still approve the PR.

2021-11-02 18:30 UTC, yp1383 commented on creation/static/map.css
> +html, body {
Yeah. I think we don't need it. Going to remove it.

2021-11-02 18:30 UTC, yp1383 commented on creation/templates/creation/_serach_page.html
> +
Done

2021-11-02 18:30 UTC, yp1383 commented on dayplanner/templates/dayplanner/base.html
> +    {%block links%} {% endblock %}
Thx!

2021-11-02 18:31 UTC, yp1383 commented on .travis.yml
> +  - pip install coverage==4.5.4
Done

2021-11-02 18:34 UTC, yp1383 commented on creation/static/map.js
> +    map = L.map('map').setView([40.7342, -74.0033], 13);
`map = L.map('map').setView([value[0]["latitude"],value[0]["longitude"]], 13)`
this one will show the first venue's coordination of the day.
`map = L.map('map').setView([40.7342, -74.0033], 13);`
if there's no venue added yet, it is set to be the Tandon's coordination

we still need a default hard-coded one before the user clicks the button "Locate Me", is that right?

2021-11-02 18:39 UTC, yp1383 commented on creation/templates/creation/mappage.html
> +    <script src="{% static 'map.js' %}"></script>
`<script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>`
if we remove this line from the `link` block, the map is not going to present.

`<script src="{% static 'map.js' %}"></script>`
If I put this line into the `link` block, the map is not going to present.

But I don't know why.

2021-11-02 18:44 UTC, yp1383 commented on creation/templates/creation/mappage.html
> +        <button style = "background-color: whtie" type = "button">
Done

2021-11-02 22:27 UTC, wangsnuxiao commented on resources/days/models.py
> +    is_active = models.BooleanField("is_active", default=True)
We can create a function that will periodically delete the days that is_active=False. I created this to act as a "Buffer" because I don't want to delete anything directly.

2021-11-02 22:29 UTC, wangsnuxiao commented on resources/venues/migrations/0002_alter_venue_yelp_id.py
> -# Generated by Django 3.2.8 on 2021-10-16 20:37
I think I deleted it because it caused a problem in my branch.

2021-11-02 22:36 UTC, wangsnuxiao commented on creation/static/map.js
> +    map = L.map('map').setView([40.7342, -74.0033], 13);
We hardcoded a default location for the map.
The logic is as follows
If Venue.size() == 0: center the map at hard-coded default location
If Venue.size() > 0: center the map at the first venue's location.

2021-11-03 02:10 UTC, sballan commented on creation/templates/creation/mappage.html
> +    <script src="{% static 'map.js' %}"></script>
I think it has to do with the order of the tags, and with the map.js file not waiting to execute before the page loads

https://stackoverflow.com/questions/436411/where-should-i-put-script-tags-in-html-markup

Here's a PR I made with a fix

2021-11-03 02:35 UTC, sballan commented on resources/days/migrations/0001_initial.py
> +        migrations.CreateModel(
I think the solution here is just to undo the commits in this branch that touch migration files, and then run `makemigrations`

2021-11-03 20:48 UTC, sballan approved these changes
Everything works great!

2021-11-03 20:49 UTC, merged